### PR TITLE
Enhance in memory operations

### PR DESCRIPTION
**Pull request by klauspost**

### CODE REVIEW

**Comment by Unknwon** [comment]
:trollface:

**Comment by klauspost** [comment]
Yeah. I forgot that PR always goes upstream ;)

This is [rclone](https://github.com/ncw/rclone/issues/317), where we want to encrypt the configuration.

Obviously we don't want the unencrypted configuration to be written to disk, so therefore I made the fork. If I clean it up a bit, and add a few tests, would you be interested in merging a PR?

**Comment by Unknwon** [comment]
> Obviously we don't want the unencrypted configuration to be written to disk, so therefore I made the fork. If I clean it up a bit, and add a few tests, would you be interested in merging a PR?

Yes, of course. :wink: As long as no API break.

**Comment by klauspost** [comment]
Very fine.

There is a current minor incompatibility I will have to work out, but I will send a PR when I am ready.

**Comment by Unknwon** [comment]
No problem :wink:

**Pull request closed without merging**
